import 'package:swipezone/repositories/location_repository.dart';
import 'package:swipezone/repositories/models/categories.dart';
import 'package:swipezone/repositories/models/localization.dart';
import 'package:swipezone/repositories/models/location.dart';

class ILocationRepository implements LocationRepository {
  @override
  Future<List<Location>> getLocations() {
    return Future.value([
    Location(
    "Tour Eiffel",
    "La Tour Eiffel est un monument emblématique de Paris, construit en 1889.",
    null,
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Eiffel_tower_from_trocadero.jpg/640px-Eiffel_tower_from_trocadero.jpg",
    Categories.Tower,
    null,
    Localization("Champ de Mars, 5 Avenue Anatole France, 75007 Paris", 48.8584, 2.2945),
    "Très populaire",
    ),
    Location(
    "Musée du Louvre",
    "Le Louvre est le plus grand musée d'art du monde, abritant la Joconde.",
    null,
    "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Louvre_Museum_Wikimedia_Commons.jpg/640px-Louvre_Museum_Wikimedia_Commons.jpg",
    Categories.Museum,
    null,
    Localization("Rue de Rivoli, 75001 Paris", 48.8606, 2.3376),
    "Très populaire",
    ),
    Location(
    "Cathédrale Notre-Dame",
    "La cathédrale gothique Notre-Dame est située sur l'île de la Cité.",
    null,
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Cathédrale_Notre_Dame%2C_Paris_30_September_2015.jpg/640px-Cathédrale_Notre_Dame%2C_Paris_30_September_2015.jpg",
    Categories.Church,
    null,
    Localization("6 Parvis Notre-Dame - Pl. Jean-Paul II, 75004 Paris", 48.8529, 2.3508),
    "Très populaire",
    ),
    Location(
    "Arc de Triomphe",
    "Construit pour honorer les victoires de Napoléon, il est situé sur la place de l'Étoile.",
    null,
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Arc_Triomphe.jpg/640px-Arc_Triomphe.jpg",
    Categories.HistoricalSite,
    null,
    Localization("Place Charles de Gaulle, 75008 Paris", 48.8738, 2.295),
    "Très populaire",
    ),
    Location(
    "Sacré-Cœur",
    "La basilique du Sacré-Cœur est un symbole religieux de Montmartre.",
    null,
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Basilique_du_Sacré-Cœur_de_Montmartre_-_Paris_-_GT-01_-_2024.jpg/640px-Basilique_du_Sacré-Cœur_de_Montmartre_-_Paris_-_GT-01_-_2024.jpg",
    Categories.Church,
    null,
    Localization("35 Rue du Chevalier de la Barre, 75018 Paris", 48.8867, 2.3431),
    "Populaire",
    ),
    Location(
    "Musée d'Orsay",
    "Le musée d'Orsay abrite des œuvres impressionnistes de Monet, Van Gogh et Renoir.",
    null,
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Pont_Royal_and_Musée_d%27Orsay%2C_Paris_10_July_2020.jpg/640px-Pont_Royal_and_Musée_d%27Orsay%2C_Paris_10_July_2020.jpg",
    Categories.Museum,
    null,
    Localization("1 Rue de la Légion d'Honneur, 75007 Paris", 48.8599, 2.3266),
    "Populaire",
    ),
    Location(
    "Château de Versailles",
    "L'ancien palais royal de Louis XIV, connu pour sa galerie des Glaces.",
    null,
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Chateau_Versailles_Galerie_des_Glaces.jpg/640px-Chateau_Versailles_Galerie_des_Glaces.jpg",
    Categories.HistoricalSite,
    null,
    Localization("Place d'Armes, 78000 Versailles", 48.8049, 2.1204),
    "Modérément populaire",
    ),
    Location(
    "Centre Pompidou",
    "Un centre culturel moderne abritant le Musée National d'Art Moderne.",
    null,
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Front_Façade_of_the_Centre_Pompidou_2.jpg/640px-Front_Façade_of_the_Centre_Pompidou_2.jpg",
    Categories.Museum,
    null,
    Localization("Place Georges-Pompidou, 75004 Paris", 48.8606, 2.3522),
    "Modérément populaire",
    ),
    Location(
    "Palais Garnier",
    "L'opéra de Paris, un chef-d'œuvre architectural du 19e siècle.",
    null,
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Opera_Garnier_Grand_Escalier.jpg/640px-Opera_Garnier_Grand_Escalier.jpg",
    Categories.HistoricalSite,
    null,
    Localization("Place de l'Opéra, 75009 Paris", 48.8710, 2.3316),
    "Modérément populaire",
    ),
    Location(
    "Jardin des Tuileries",
    "Un grand jardin public situé entre le Louvre et la Place de la Concorde.",
    null,
    "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Pavillon_de_Flore_from_the_Tuileries_Garden%2C_Paris_5_November_2019.jpg/640px-Pavillon_de_Flore_from_the_Tuileries_Garden%2C_Paris_5_November_2019.jpg",
    Categories.Park,
    null,
    Localization("Place de la Concorde, 75001 Paris", 48.8634, 2.3255),
    "Populaire",
    ),
    Location(
    "Catacombes de Paris",
    "Un réseau souterrain de tunnels et de chambres remplis d'ossements.",
    null,
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Katakomben_catacombes_paris_2011.jpg/640px-Katakomben_catacombes_paris_2011.jpg",
    Categories.HistoricalSite,
    null,
    Localization("1 Avenue du Colonel Henri Rol-Tanguy, 75014 Paris", 48.8339, 2.3324),
    "Modérément populaire",
    ),
    Location(
    "Sainte-Chapelle",
    "Une chapelle royale gothique connue pour ses magnifiques vitraux.",
    null,
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Interior_of_Saint-Chapelle_in_Paris.jpg/640px-Interior_of_Saint-Chapelle_in_Paris.jpg",
    Categories.Church,
    null,
    Localization("10 Boulevard du Palais, 75001 Paris", 48.8554, 2.3451),
    "Modérément populaire",
    ),
      Location(
        "Musée Rodin",
        "Un musée dédié aux œuvres du sculpteur Auguste Rodin.",
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/L%27hôtel_Biron_%28musée_Rodin%29_à_Paris%2C_13_juin_2021_01.jpg/640px-L%27hôtel_Biron_%28musée_Rodin%29_à_Paris%2C_13_juin_2021_01.jpg",
        Categories.Museum,
        null,
        Localization("77 Rue de Varenne, 75007 Paris", 48.8555, 2.3155),
        "Modérément populaire",
      ),
      Location(
        "Panthéon",
        "Un monument néoclassique servant de mausolée pour les figures françaises illustres.",
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Pantheon_of_Paris_007.JPG/640px-Pantheon_of_Paris_007.JPG",
        Categories.HistoricalSite,
        null,
        Localization("Place du Panthéon, 75005 Paris", 48.8462, 2.3464),
        "Populaire",
      ),
      Location(
        "Pont Alexandre III",
        "Un pont orné enjambant la Seine, offrant une vue spectaculaire sur les Invalides.",
        null,
        "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Pont_Alexandre_III%2C_Paris_8th_025.JPG/640px-Pont_Alexandre_III%2C_Paris_8th_025.JPG",
        Categories.HistoricalSite,
        null,
        Localization("Pont Alexandre III, 75008 Paris", 48.8637, 2.3136),
        "Populaire",
      ),
    ]);
  }
}